# Nombre de la aplicación dentro del contexto de Spring Boot
spring.application.name=foroHub


# URL de conexión a la base de datos MySQL
# jdbc:mysql://localhost/forohub  -> conecta a la base de datos llamada "forohub"
# createDatabaseIfNotExist=true   -> si la base de datos no existe, MySQL la crea automáticamente
# serverTimezone=UTC              -> evita problemas de zona horaria con fechas
spring.datasource.url=jdbc:mysql://localhost/forohub?createDatabaseIfNotExist=true&serverTimezone=UTC


# Usuario de la base de datos
spring.datasource.username=root


# Contraseña del usuario de la base de datos
spring.datasource.password=123456


# Controla cómo Hibernate maneja el esquema de la base de datos
# validate -> verifica que las tablas existentes coincidan con las entidades
# NO crea ni modifica tablas (porque eso lo hace Flyway)
spring.jpa.hibernate.ddl-auto=validate


# Muestra en consola las consultas SQL que ejecuta Hibernate
# Muy útil para desarrollo y debugging
spring.jpa.show-sql=true


# Formatea el SQL mostrado en consola para que sea más legible
spring.jpa.properties.hibernate.format_sql=true


# Controla si Spring muestra el stacktrace en los errores HTTP
# never -> nunca muestra el stacktrace al cliente (buena práctica de seguridad)
server.error.include-stacktrace=never

api.security.secret=${JWT_SECRET:123456}

